/* Auto-generated by @antadesign/anta. Do not edit by hand. */

import type { IconShapes } from '@antadesign/anta'

export const ICON_SHAPES = [
  'banner',
  'book-a',
  'card',
  'chevrons-right',
  'chevrons-up-down-square',
  'circle-pause',
  'circle-play',
  'clipboard-paste',
  'dialog',
  'footprints',
  'loader-docs',
  'octagon-pause',
  'search-slash',
  'settings-2',
  'square-chevron-down',
  'square-chevron-right',
  'sticker',
  'tabs',
  'theme',
  'toaster',
] as const

export const ICON_SYNONYMS: Readonly<Record<string, readonly string[]>> = {
}

declare module '@antadesign/anta' {
  interface IconShapes {
    'banner': true
    'book-a': true
    'card': true
    'chevrons-right': true
    'chevrons-up-down-square': true
    'circle-pause': true
    'circle-play': true
    'clipboard-paste': true
    'dialog': true
    'footprints': true
    'loader-docs': true
    'octagon-pause': true
    'search-slash': true
    'settings-2': true
    'square-chevron-down': true
    'square-chevron-right': true
    'sticker': true
    'tabs': true
    'theme': true
    'toaster': true
  }
}

export type IconShape = keyof IconShapes
