/* Auto-generated by scripts/generate-icons.mjs. Do not edit by hand. */

export const ICON_SHAPES = [
  'arrow-left-to-line',
  'arrow-left',
  'arrow-narrow-down',
  'arrow-narrow-up-down',
  'arrow-narrow-up',
  'arrow-right',
  'arrow-top-right',
  'asterisk',
  'book-open',
  'braces',
  'bug',
  'calendar',
  'case-sensitive',
  'chat',
  'check',
  'chevron-down',
  'chevron-left',
  'chevron-right',
  'chevron-up',
  'chevrons-right',
  'circle-check',
  'circle-large',
  'circle',
  'click',
  'clock',
  'cloud-upload',
  'copy',
  'corner-down-right',
  'cube',
  'dots-vertical',
  'download',
  'edit',
  'education-disk',
  'external-link',
  'file-down',
  'file',
  'filter',
  'folder-close',
  'folder-open',
  'folder-tree',
  'github-logo',
  'gitlab-logo',
  'help-disk',
  'history-tree',
  'history',
  'home',
  'info',
  'jira-logo',
  'linear-logo',
  'link',
  'list-detail-view',
  'maximize',
  'megaphone',
  'menu',
  'minimize',
  'minus',
  'more',
  'move-horizontal',
  'not-equal',
  'play',
  'plus',
  'presentation',
  'refresh',
  'regex',
  'repeat',
  'rss',
  'runs-history',
  'scroll-text',
  'search-check',
  'search',
  'send',
  'sparkles',
  'text-highlight',
  'timer',
  'trash',
  'trello-logo',
  'view',
  'warning-triangle',
  'webhook',
  'workflow',
  'x',
] as const

export const ICON_SYNONYMS: Readonly<Record<string, readonly string[]>> = {
  'chevron-down': ['arrow', 'expand', 'open', 'down'],
  'chevron-up': ['arrow', 'collapse', 'close', 'up'],
  'chevron-left': ['arrow', 'back', 'previous'],
  'chevron-right': ['arrow', 'forward', 'next'],
  'chevrons-right': ['skip', 'fast forward'],
  'arrow-narrow-down': ['download', 'fall', 'down'],
  'arrow-narrow-up': ['upload', 'rise', 'up'],
  'arrow-left': ['back', 'previous', 'prev'],
  'arrow-right': ['forward', 'next'],
  'arrow-narrow-up-down': ['sort', 'swap', 'transfer', 'reorder'],
  'arrow-top-right': ['external', 'open', 'leave'],
  'arrow-left-to-line': ['dock', 'snap', 'align'],
  'move-horizontal': ['resize', 'swap', 'horizontal'],
  'external-link': ['open', 'link', 'share', 'outbound'],
  'check': ['tick', 'ok', 'done', 'confirm', 'approve'],
  'circle-check': ['success', 'ok', 'done'],
  'x': ['close', 'cancel', 'dismiss', 'remove', 'no'],
  'plus': ['add', 'new', 'create'],
  'minus': ['remove', 'subtract'],
  'menu': ['hamburger', 'list', 'more'],
  'dots-vertical': ['more', 'kebab', 'options'],
  'search': ['find', 'magnify', 'lookup'],
  'search-check': ['found', 'validated'],
  'copy': ['duplicate', 'clone'],
  'trash': ['delete', 'remove', 'bin'],
  'edit': ['pencil', 'modify', 'rename'],
  'view': ['eye', 'show', 'display', 'preview'],
  'click': ['tap', 'press', 'touch'],
  'send': ['submit', 'share', 'deliver'],
  'play': ['start', 'run', 'execute'],
  'refresh': ['reload', 'sync', 'update'],
  'regex': ['pattern', 'match'],
  'repeat': ['loop', 'retry', 'rerun'],
  'info': ['information', 'about', 'i'],
  'warning-triangle': ['alert', 'danger', 'caution'],
  'bug': ['defect', 'issue', 'error'],
  'asterisk': ['star', 'wildcard'],
  'braces': ['code', 'brackets', 'json'],
  'case-sensitive': ['aA', 'capitalize', 'case'],
  'text-highlight': ['mark', 'highlight'],
  'list-detail-view': ['list', 'items'],
  'folder-open': ['directory', 'browse'],
  'folder-close': ['directory'],
  'folder-tree': ['hierarchy', 'structure', 'tree'],
  'file': ['document', 'page'],
  'file-down': ['download', 'save'],
  'calendar': ['date', 'schedule'],
  'clock': ['time'],
  'timer': ['stopwatch', 'countdown', 'time'],
  'history': ['log', 'past'],
  'history-tree': ['log', 'past'],
  'runs-history': ['log', 'past'],
  'github-logo': ['github', 'git', 'repo'],
  'gitlab-logo': ['gitlab', 'git', 'repo'],
  'trello-logo': ['trello', 'board', 'kanban'],
  'jira-logo': ['jira', 'ticket', 'issue'],
  'linear-logo': ['linear', 'ticket', 'issue'],
  'chat': ['message', 'comment', 'discuss'],
  'presentation': ['slides', 'deck'],
  'education-disk': ['learn', 'school', 'academic'],
  'book-open': ['read', 'docs', 'documentation'],
  'help-disk': ['question', 'faq', 'support', 'help'],
  'sparkles': ['ai', 'magic', 'generate'],
  'cube': ['box', 'package'],
  'circle': ['dot', 'point'],
  'circle-large': ['dot', 'marker'],
  'not-equal': ['neq', 'different'],
  'corner-down-right': ['branch', 'indent', 'return'],
  'rss': ['feed', 'subscribe'],
  'scroll-text': ['log', 'output', 'console'],
  'workflow': ['pipeline', 'process', 'flow'],
  'webhook': ['integration', 'hook'],
  'megaphone': ['announcement', 'broadcast'],
  'maximize': ['fullscreen', 'expand'],
  'minimize': ['collapse', 'shrink'],
  'filter': ['sort', 'narrow'],
  'download': ['save', 'import'],
  'cloud-upload': ['save', 'sync', 'upload', 'send', 'export'],
  'link': ['url', 'href', 'anchor'],
  'more': ['options', 'extra'],
}

declare module '@antadesign/anta' {
  interface IconShapes {
    'arrow-left-to-line': true
    'arrow-left': true
    'arrow-narrow-down': true
    'arrow-narrow-up-down': true
    'arrow-narrow-up': true
    'arrow-right': true
    'arrow-top-right': true
    'asterisk': true
    'book-open': true
    'braces': true
    'bug': true
    'calendar': true
    'case-sensitive': true
    'chat': true
    'check': true
    'chevron-down': true
    'chevron-left': true
    'chevron-right': true
    'chevron-up': true
    'chevrons-right': true
    'circle-check': true
    'circle-large': true
    'circle': true
    'click': true
    'clock': true
    'cloud-upload': true
    'copy': true
    'corner-down-right': true
    'cube': true
    'dots-vertical': true
    'download': true
    'edit': true
    'education-disk': true
    'external-link': true
    'file-down': true
    'file': true
    'filter': true
    'folder-close': true
    'folder-open': true
    'folder-tree': true
    'github-logo': true
    'gitlab-logo': true
    'help-disk': true
    'history-tree': true
    'history': true
    'home': true
    'info': true
    'jira-logo': true
    'linear-logo': true
    'link': true
    'list-detail-view': true
    'maximize': true
    'megaphone': true
    'menu': true
    'minimize': true
    'minus': true
    'more': true
    'move-horizontal': true
    'not-equal': true
    'play': true
    'plus': true
    'presentation': true
    'refresh': true
    'regex': true
    'repeat': true
    'rss': true
    'runs-history': true
    'scroll-text': true
    'search-check': true
    'search': true
    'send': true
    'sparkles': true
    'text-highlight': true
    'timer': true
    'trash': true
    'trello-logo': true
    'view': true
    'warning-triangle': true
    'webhook': true
    'workflow': true
    'x': true
  }
}

export type IconShape = keyof import('@antadesign/anta').IconShapes
