/* Auto-generated by @antadesign/anta. Do not edit by hand. */

import type { IconShapes } from '@antadesign/anta'

export const ICON_SHAPES = [
  'arrow-left-to-line',
  'arrow-left',
  'arrow-narrow-down',
  'arrow-narrow-up-down',
  'arrow-narrow-up',
  'arrow-right',
  'arrow-top-right',
  'asterisk',
  'blank',
  'book-open',
  'braces',
  'bug',
  'calendar-days',
  'calendar',
  'case-sensitive',
  'chat',
  'check',
  'chevron-down',
  'chevron-left',
  'chevron-right',
  'chevron-up',
  'chevrons-right',
  'circle-check',
  'circle-dot',
  'circle-large',
  'circle-small-solid',
  'circle-user',
  'circle',
  'click',
  'clock',
  'cloud-upload',
  'columns-3-cog',
  'copy',
  'corner-down-right',
  'cube',
  'dollar-sign',
  'dots-vertical',
  'download',
  'edit',
  'external-link',
  'eye-closed',
  'eye',
  'file-down',
  'file',
  'filter-x',
  'filter',
  'folder-close',
  'folder-open',
  'folder-tree',
  'hat-glasses',
  'heart-handshake',
  'heart',
  'history-tree',
  'history',
  'home',
  'hourglass',
  'info',
  'link',
  'list-collapse',
  'maximize',
  'megaphone',
  'menu',
  'minimize',
  'minus',
  'moon',
  'more',
  'move-horizontal',
  'not-equal',
  'play',
  'plus',
  'pointer',
  'presentation',
  'refresh-ccw-dot',
  'refresh',
  'regex',
  'repeat',
  'rotate-ccw',
  'rss',
  'runs-history',
  'scroll-text',
  'search-check',
  'search',
  'send',
  'settings',
  'share',
  'sparkles',
  'square-check-big',
  'square-menu',
  'sun',
  'swatch-book',
  'table-2',
  'tag',
  'text-cursor-input',
  'text-initial',
  'timer',
  'toggle-right',
  'trash',
  'view',
  'warning-diamond',
  'warning-triangle',
  'webhook',
  'workflow',
  'x',
] as const

export const ICON_SYNONYMS: Readonly<Record<string, readonly string[]>> = {
  'columns-3-cog': ['columns', 'table', 'settings', 'configure', 'fields', 'visibility'],
  'blank': ['spacer', 'empty', 'placeholder', 'space', 'none'],
  'warning-diamond': ['error', 'invalid', 'alert', 'danger'],
  'swatch-book': ['palette', 'color', 'swatch', 'paint', 'design'],
  'hat-glasses': ['accessibility', 'vision', 'disguise', 'person'],
  'heart-handshake': ['credits', 'thanks', 'agreement', 'deal', 'partnership'],
  'heart': ['like', 'favorite', 'love', 'wishlist'],
  'hourglass': ['progress', 'time', 'wait', 'loading', 'timer'],
  'text-initial': ['text', 'typography', 'letter', 'a'],
  'chevron-down': ['arrow', 'expand', 'open', 'down'],
  'chevron-up': ['arrow', 'collapse', 'close', 'up'],
  'chevron-left': ['arrow', 'back', 'previous'],
  'chevron-right': ['arrow', 'forward', 'next'],
  'chevrons-right': ['skip', 'fast forward'],
  'arrow-narrow-down': ['download', 'fall', 'down'],
  'arrow-narrow-up': ['upload', 'rise', 'up'],
  'arrow-left': ['back', 'previous', 'prev'],
  'arrow-right': ['forward', 'next'],
  'arrow-narrow-up-down': ['sort', 'swap', 'transfer', 'reorder'],
  'arrow-top-right': ['external', 'open', 'leave'],
  'arrow-left-to-line': ['dock', 'snap', 'align'],
  'move-horizontal': ['resize', 'swap', 'horizontal'],
  'external-link': ['open', 'link', 'share', 'outbound'],
  'check': ['tick', 'ok', 'done', 'confirm', 'approve'],
  'dollar-sign': ['currency', 'money', 'payment'],
  'circle-check': ['success', 'ok', 'done'],
  'circle-user': ['avatar', 'person', 'account', 'contact', 'profile'],
  'x': ['close', 'cancel', 'dismiss', 'remove', 'no'],
  'plus': ['add', 'new', 'create'],
  'minus': ['remove', 'subtract'],
  'menu': ['hamburger', 'list', 'more'],
  'dots-vertical': ['more', 'kebab', 'options'],
  'search': ['find', 'magnify', 'lookup'],
  'search-check': ['found', 'validated'],
  'copy': ['duplicate', 'clone'],
  'trash': ['delete', 'remove', 'bin'],
  'edit': ['pencil', 'modify', 'rename'],
  'view': ['show', 'display', 'preview'],
  'click': ['tap', 'press', 'touch'],
  'send': ['submit', 'share', 'deliver'],
  'play': ['start', 'run', 'execute'],
  'refresh': ['reload', 'sync', 'update'],
  'regex': ['pattern', 'match'],
  'repeat': ['loop', 'retry', 'rerun'],
  'info': ['information', 'about', 'i'],
  'warning-triangle': ['alert', 'danger', 'caution'],
  'bug': ['defect', 'issue', 'error'],
  'asterisk': ['star', 'wildcard'],
  'braces': ['code', 'brackets', 'json'],
  'case-sensitive': ['aA', 'capitalize', 'case'],
  'list-collapse': ['list', 'collapse', 'expand', 'items'],
  'table-2': ['table', 'grid', 'data', 'spreadsheet', 'rows', 'columns'],
  'folder-open': ['directory', 'browse'],
  'folder-close': ['directory'],
  'folder-tree': ['hierarchy', 'structure', 'tree'],
  'file': ['document', 'page'],
  'file-down': ['download', 'save'],
  'calendar': ['date', 'schedule'],
  'clock': ['time'],
  'timer': ['stopwatch', 'countdown', 'time'],
  'toggle-right': ['toggle', 'switch', 'on', 'off', 'boolean'],
  'history': ['log', 'past'],
  'history-tree': ['log', 'past'],
  'runs-history': ['log', 'past'],
  'chat': ['message', 'comment', 'discuss'],
  'presentation': ['slides', 'deck'],
  'book-open': ['read', 'docs', 'documentation'],
  'sparkles': ['ai', 'magic', 'generate'],
  'cube': ['box', 'package'],
  'circle': ['dot', 'point'],
  'circle-large': ['dot', 'marker'],
  'not-equal': ['neq', 'different'],
  'corner-down-right': ['branch', 'indent', 'return'],
  'rss': ['feed', 'subscribe'],
  'scroll-text': ['log', 'output', 'console'],
  'workflow': ['pipeline', 'process', 'flow'],
  'webhook': ['integration', 'hook'],
  'megaphone': ['announcement', 'broadcast'],
  'maximize': ['fullscreen', 'expand'],
  'minimize': ['collapse', 'shrink'],
  'filter': ['sort', 'narrow'],
  'filter-x': ['clear filter', 'reset filter', 'remove filter'],
  'download': ['save', 'import'],
  'cloud-upload': ['save', 'sync', 'upload', 'send', 'export'],
  'link': ['url', 'href', 'anchor'],
  'more': ['options', 'extra'],
  'tag': ['label', 'badge', 'chip'],
}

declare module '@antadesign/anta' {
  interface IconShapes {
    'arrow-left-to-line': true
    'arrow-left': true
    'arrow-narrow-down': true
    'arrow-narrow-up-down': true
    'arrow-narrow-up': true
    'arrow-right': true
    'arrow-top-right': true
    'asterisk': true
    'blank': true
    'book-open': true
    'braces': true
    'bug': true
    'calendar-days': true
    'calendar': true
    'case-sensitive': true
    'chat': true
    'check': true
    'chevron-down': true
    'chevron-left': true
    'chevron-right': true
    'chevron-up': true
    'chevrons-right': true
    'circle-check': true
    'circle-dot': true
    'circle-large': true
    'circle-small-solid': true
    'circle-user': true
    'circle': true
    'click': true
    'clock': true
    'cloud-upload': true
    'columns-3-cog': true
    'copy': true
    'corner-down-right': true
    'cube': true
    'dollar-sign': true
    'dots-vertical': true
    'download': true
    'edit': true
    'external-link': true
    'eye-closed': true
    'eye': true
    'file-down': true
    'file': true
    'filter-x': true
    'filter': true
    'folder-close': true
    'folder-open': true
    'folder-tree': true
    'hat-glasses': true
    'heart-handshake': true
    'heart': true
    'history-tree': true
    'history': true
    'home': true
    'hourglass': true
    'info': true
    'link': true
    'list-collapse': true
    'maximize': true
    'megaphone': true
    'menu': true
    'minimize': true
    'minus': true
    'moon': true
    'more': true
    'move-horizontal': true
    'not-equal': true
    'play': true
    'plus': true
    'pointer': true
    'presentation': true
    'refresh-ccw-dot': true
    'refresh': true
    'regex': true
    'repeat': true
    'rotate-ccw': true
    'rss': true
    'runs-history': true
    'scroll-text': true
    'search-check': true
    'search': true
    'send': true
    'settings': true
    'share': true
    'sparkles': true
    'square-check-big': true
    'square-menu': true
    'sun': true
    'swatch-book': true
    'table-2': true
    'tag': true
    'text-cursor-input': true
    'text-initial': true
    'timer': true
    'toggle-right': true
    'trash': true
    'view': true
    'warning-diamond': true
    'warning-triangle': true
    'webhook': true
    'workflow': true
    'x': true
  }
}

export type IconShape = keyof IconShapes
